---
- import_playbook: playbooks/lb.yml
- import_playbook: playbooks/all.yml
# - import_playbook: playbooks/monitor.yml
# - import_playbook: playbooks/mgmt.yml
# - import_playbook: playbooks/docker.yml
# - import_playbook: playbooks/db.yml
